// <auto-generated />
using System;
using Helpdesk;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Helpdesk.Migrations
{
    [DbContext(typeof(HelpdeskDbContext))]
    partial class HelpdeskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Helpdesk.Models.ChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("IssueId")
                        .HasColumnType("bigint");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("SenderId");

                    b.ToTable("ChatMessage");
                });

            modelBuilder.Entity("Helpdesk.Models.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("FileContent")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("IssueId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("Helpdesk.Models.Issue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AssigneeId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<long>("RequesterId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("RequesterId");

                    b.ToTable("Issues", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AssigneeId = 3L,
                            CreatedDate = new DateOnly(2025, 7, 1),
                            Description = "Uživatel hlásí, že se nemůže přihlásit do systému.",
                            DueDate = new DateOnly(2025, 7, 7),
                            Priority = 2,
                            RequesterId = 2L,
                            Status = 0,
                            Title = "Problém s přihlášením"
                        },
                        new
                        {
                            Id = 2L,
                            AssigneeId = 3L,
                            CreatedDate = new DateOnly(2025, 7, 2),
                            Description = "Firma nahlásila špatně spočítanou fakturu.",
                            DueDate = new DateOnly(2025, 7, 20),
                            Priority = 1,
                            RequesterId = 1L,
                            Status = 1,
                            Title = "Chyba ve fakturaci"
                        },
                        new
                        {
                            Id = 3L,
                            AssigneeId = 1L,
                            CreatedDate = new DateOnly(2025, 7, 1),
                            Description = "Zaměstnanec požaduje nové pracovní zařízení.",
                            DueDate = new DateOnly(2025, 7, 20),
                            Priority = 0,
                            RequesterId = 3L,
                            Status = 0,
                            Title = "Požadavek na nové zařízení"
                        });
                });

            modelBuilder.Entity("Helpdesk.Models.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdentificationNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsApplicationAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CompanyName = "Testovací Firma s.r.o.",
                            Email = "firma@example.com",
                            IdentificationNumber = 12345678,
                            IsApplicationAdmin = false,
                            PersonType = 1
                        },
                        new
                        {
                            Id = 2L,
                            DateOfBirth = new DateOnly(1985, 5, 20),
                            Email = "jan.novak@example.com",
                            FirstName = "Jan",
                            IsApplicationAdmin = true,
                            LastName = "Novák",
                            PersonType = 0
                        },
                        new
                        {
                            Id = 3L,
                            DateOfBirth = new DateOnly(1990, 8, 15),
                            Email = "petr.svoboda@example.com",
                            FirstName = "Petr",
                            IsApplicationAdmin = false,
                            LastName = "Svoboda",
                            PersonType = 0
                        });
                });

            modelBuilder.Entity("Helpdesk.Models.SubIssue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<long>("IssueId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.ToTable("SubIssues", (string)null);
                });

            modelBuilder.Entity("Helpdesk.Models.ChatMessage", b =>
                {
                    b.HasOne("Helpdesk.Models.Issue", null)
                        .WithMany("Chat")
                        .HasForeignKey("IssueId");

                    b.HasOne("Helpdesk.Models.Person", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Helpdesk.Models.Document", b =>
                {
                    b.HasOne("Helpdesk.Models.Issue", null)
                        .WithMany("Documents")
                        .HasForeignKey("IssueId");
                });

            modelBuilder.Entity("Helpdesk.Models.Issue", b =>
                {
                    b.HasOne("Helpdesk.Models.Person", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Helpdesk.Models.Person", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Helpdesk.Models.SubIssue", b =>
                {
                    b.HasOne("Helpdesk.Models.Issue", "Issue")
                        .WithMany("SubIssues")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Helpdesk.Models.Issue", b =>
                {
                    b.Navigation("Chat");

                    b.Navigation("Documents");

                    b.Navigation("SubIssues");
                });
#pragma warning restore 612, 618
        }
    }
}
